language: node_js
node_js:
  - "5.0"
  - "4.0"
  - "0.12"
  - "0.10"

services:
  - postgresql
  - mongodb
  - mysql
  - redis-server

addons:
  postgresql: "9.4"

env:
  - DB_USER=postgres DB_PASS=''

# run in docker
sudo: false

before_script:
  - npm install balderdashy/waterline
  - psql -c 'create database sailspg;' -U postgres
  - mysql -e 'create database sails_mysql;'
